const lang = {
  en: {
    home: "Home",
    aboutus: "About Us",
    services: "Services",
    doctor: "Doctor",
    login: "Login",
    connectwithus: "Connect with Us",
    name: "Name",
    email: "Email",
    phonenumber: "Phone Number",
    message: "Message",
    submitnow: "Submit Now",
    conveyyour: "Convey Your",
    ideastous: "Ideas To Us",
    getintouch: "GET IN TOUCH",
    connecting: "Connecting",
    patients: "Patients",
    toqualitycare: "To Quality Care",
    submit: "Submit",
    maincontainerslogan:
      "Your trusted partner in health and wellness, providing expert care and personalized treatment plans. Together, we prioritize your well-being, ensuring a healthier, happier tomorrow.",
    enquirynow: "Enquiry Now",
    address: "456 Lotus Street, Block C, Sector 22, Haryana",
    contactpageslogan:
      "Contact us for questions, technical assistance, or collaboration opportunities via the contact information provided.",
    profile: "Profile",
    login: "Login",
    languages: "Languages",
    password:"Password",
    forgotpassword: "Forgot Password",
    resetpassword: "Reset Password",
    changepassword: "Change Password",
    signUp:"Sign Up",
    remember:"Remember Me",
    haveAccount : "Already have an account",
    signIn :"Sign In",
    buyNow :"Buy Now",
    shopping:"Shopping",
    glucosemeter:"Glucose Meter: Stay in control of your health with our advanced glucose meter, designed for quick and accurate blood sugar monitoring. Ideal for diabetes management, it requires a simple fingertip prick to deliver precise readings. Compact and easy to use, this essential device helps you track your glucose levels effortlessly. With features like digital displays, memory storage, and smartphone connectivity, managing your blood sugar has never been easier or more convenient",
    bloodpressuremonitor:"Blood Pressure Monitor: Keep a close watch on your heart health with our reliable blood pressure monitor. Offering accurate and fast results, this user-friendly device tracks your systolic and diastolic pressures, as well as heart rate, from the comfort of your home. Its digital display and memory function make it easy to monitor trends over time, helping you stay informed and in control",
    thermometer:"Thermometer: Ensure the well-being of your family with our easy-to-use thermometer, designed for fast and precise temperature readings. Whether you’re checking for fever or tracking body temperature changes, this essential tool provides accurate results in seconds. With digital displays and memory recall, staying on top of your health has never been simpler",
    covidtestkit:"COVID Test Kit: Safeguard yourself and those around you with our reliable COVID test kit, providing quick and accurate results from the comfort of your home. With easy instructions and fast testing capabilities, you can detect the presence of the virus in minutes, allowing for timely decisions about health and safety. A must-have for anyone prioritizing public health and well-being",
    firstaidkit:"First Aid Kit: Be prepared for minor injuries and emergencies with our comprehensive first aid kit. Stocked with essential medical supplies like bandages, antiseptic wipes, and more, this kit provides everything you need for on-the-spot treatment. Compact and portable, it’s perfect for home, travel, or outdoor activities, ensuring you’re always ready to handle unexpected situations",
    pulseoximeter:"Pulse Oximeter: Keep an eye on your oxygen levels and heart rate with our compact and easy-to-use pulse oximeter. This non-invasive device delivers quick and accurate readings with just a fingertip placement, allowing you to monitor your health at any time. Ideal for respiratory conditions and fitness tracking, it’s a vital tool for maintaining wellness",
    pregnancytestkit:"Pregnancy Test Kit: Get clear and reliable results with our easy-to-use pregnancy test kit, designed to deliver accurate answers quickly. With simple instructions and high sensitivity, it provides peace of mind by confirming pregnancy within minutes. Discreet and dependable, it’s the ideal companion for women seeking accurate reproductive health information",
    whoarewe : "Who We Are",
    whoarewecontent1 : "Medicoz offers a comprehensive health platform that leverages machine learning to provide personalized disease severity predictions, helping users manage conditions like diabetes, hypertension, heart disease, etc",
    whoarewecontent2 : "The platform connects users with top doctors and clinics based on their health needs and offers a convenient shopping option for essential health monitoring devices",
    whoarewepoint1 : "Personalized disease predictions with AI insights",
    whoarewepoint2 : "Empowering informed health decisions for users",
    whoarewepoint3 : "Connect with top doctors and clinics in the country",
    whoarewepoint4 : "Shop essential health devices effortlessly online",
    whoarewepoint5 : "Tailored provider recommendations for better care",
    whoarewepoint6 : "Accurate insights for proactive health management",
    weoffer:"We Offer Different Services ",
    toimprove:"To Improve Your Health",
    keepup:"Keep Up With Our Most Recent Medical News",
    tagline: "Diagnosing Today Securing Tomorrow",
     "address": "456 Lotus Street, Block C, Sector 22, Gurugram, Haryana, 122001, India",
  "followus": "Follow us on Instagram",
  trustus:"Your trusted partner in health and wellness, providing expert care and personalized treatment plans. Together, we prioritize your well-being, ensuring a healthier, happier tomorrow",
  servicesContent: "At Medicoz, we provide a comprehensive range of services designed to improve health outcomes and manage chronic diseases effectively. Our expert team of healthcare professionals combines personalized care with the latest medical technology to offer the following services:",
  hypertensionService: "We offer personalized monitoring and treatment plans for blood pressure management, with regular consultations from cardiologists and dieticians. You can access home blood pressure monitoring devices and participate in lifestyle modification programs designed to help control hypertension.",
  dementiaService: "For dementia care, we provide cognitive rehabilitation programs aimed at slowing the progression of the disease. Our specialized memory care services ensure round-the-clock support, while caregivers are guided on creating a safe and supportive environment for patients.",
  aidsService: "We offer comprehensive HIV/AIDS care, including access to antiretroviral therapy (ART) to manage the disease effectively. Regular health check-ups monitor immune function and viral load, and our counseling services provide mental health support and lifestyle advice for patients.",
  heartDiseaseService: "We provide full heart health screenings, including cholesterol and stress tests, as well as treatments ranging from medication to advanced procedures like angioplasty. Our cardiac rehabilitation programs support recovery and prevent future heart disease incidents.",
  diabetesService: "Our diabetes management services include blood sugar monitoring with access to advanced glucose meters. We create personalized meal plans and exercise regimens and offer diabetes education programs to help you understand and manage your condition effectively.",
  strokeService: "To prevent strokes, we offer stroke risk assessments and management of contributing factors. We also provide physical and occupational therapy to aid recovery after a stroke, and our emergency care services ensure quick intervention during stroke events.",
  thyroidService: "For thyroid disorders, we provide regular thyroid function tests to monitor hormone levels and manage medication for conditions like hypothyroidism and hyperthyroidism. Consultations with endocrinologists ensure specialized care and treatment adjustments as needed.",
  asthmaService: "Our asthma control programs offer personalized action plans with regular lung function testing. We provide access to inhalers, nebulizers, and advanced breathing treatments, along with allergy testing and immunotherapy to reduce asthma triggers.",
  breastCancerService: "For breast cancer, we offer early detection services including mammograms and breast exams. Access to leading oncologists ensures personalized treatment plans, and we provide post-surgical care, chemotherapy, and radiation therapy services as needed.",
  lungCancerService: "We provide advanced imaging and biopsy services for early lung cancer detection. Patients have access to cutting-edge treatments such as targeted therapy and immunotherapy, as well as smoking cessation programs and lung health screenings to support prevention and recovery.",
  hypertension: "Patients with hypertension have appreciated telehealth services for offering remote blood pressure monitoring and easy access to specialists. The ability to track readings in real-time has improved condition management, reducing the need for frequent in-person visits.",
  diabetes:"Diabetic patients appreciate being able to monitor their blood sugar remotely via connected devices. Telehealth services have improved medication management and allowed for personalized nutritional consultations.",
  asthma: "Asthma patients appreciate the personalized action plans offered through telehealth platforms. Remote lung function testing and access to inhalers or nebulizers have improved their ability to manage the condition effectively.",

  },

  हिन्दी: {
    home: "होम",
    aboutus: "हमारे बारे में",
    services: "सेवाएं",
    doctor: "चिकित्सक",
    login: "लॉग इन",
    connectwithus: "हमारे साथ जुड़ें",
    name: "नाम",
    email: "ईमेल",
    phonenumber: "फ़ोन नंबर",
    message: "संदेश",
    submitnow: "जमा करें",
    conveyyour: "अपने विचार",
    ideastous: "हमें बताएं",
    getintouch: "संपर्क में रहे",
    submit: "जमा करें",
    connecting: "मरीजों को",
    patients: "गुणवत्तापूर्ण ",
    toqualitycare: "देखभाल से जोड़ना",
    maincontainerslogan:
      "स्वास्थ्य और कल्याण में आपका विश्वसनीय भागीदार, विशेषज्ञ देखभाल और वैयक्तिकृत उपचार योजनाएँ प्रदान करता है। साथ मिलकर, हम एक स्वस्थ, खुशहाल कल सुनिश्चित करते हुए आपकी भलाई को प्राथमिकता देते हैं।",
    enquirynow: "अभी पूछताछ करें",
    address: "456 लोटस स्ट्रीट, ब्लॉक सी, सेक्टर 22, हरयाणा",
    contactpageslogan:
      "प्रश्नों, तकनीकी सहायता, या सहयोग के अवसरों के लिए प्रदान की गई संपर्क जानकारी के माध्यम से हमसे संपर्क करें।",
    profile: "प्रोफ़ाइल",
    login: "लॉगिन",
    languages: "भाषा",
      password: "पासवर्ड",
      forgotpassword: "पासवर्ड भूल गए",
      resetpassword: "पासवर्ड रीसेट करें",
      changepassword: "पासवर्ड बदलें",
      signUp: "साइन अप करें",
      remember: "मुझे याद रखें",
      haveAccount: "पहले से खाता है",
      signIn: "साइन इन करें",
      buyNow: "अभी खरीदें",
      shopping: "खरीदारी",
      glucosemeter: "ग्लूकोज मीटर: हमारी उन्नत ग्लूकोज मीटर के साथ अपने स्वास्थ्य पर नियंत्रण रखें, जो त्वरित और सटीक रक्त शर्करा की निगरानी के लिए डिज़ाइन किया गया है। मधुमेह प्रबंधन के लिए आदर्श, यह उपकरण सरल फिंगरप्रिक से सटीक रीडिंग देता है। कॉम्पैक्ट और उपयोग में आसान, यह आवश्यक उपकरण आपको अपने ग्लूकोज स्तर को आसानी से ट्रैक करने में मदद करता है। डिजिटल डिस्प्ले, मेमोरी स्टोरेज, और स्मार्टफोन कनेक्टिविटी जैसी सुविधाओं के साथ, आपके रक्त शर्करा का प्रबंधन पहले से कहीं अधिक आसान और सुविधाजनक हो गया है।",
      bloodpressuremonitor: "ब्लड प्रेशर मॉनिटर: अपने दिल के स्वास्थ्य पर नज़र रखें हमारे विश्वसनीय ब्लड प्रेशर मॉनिटर के साथ। यह उपयोगकर्ता के अनुकूल उपकरण सटीक और त्वरित परिणाम प्रदान करता है, जिससे आप घर बैठे सिस्टोलिक और डायस्टोलिक दबाव के साथ-साथ हृदय गति की निगरानी कर सकते हैं। इसका डिजिटल डिस्प्ले और मेमोरी फ़ंक्शन समय के साथ रुझानों की निगरानी को आसान बनाता है, जिससे आप हमेशा सूचित और नियंत्रण में रह सकते हैं।",
      thermometer: "थर्मामीटर: हमारे आसान-से-उपयोग वाले थर्मामीटर के साथ अपने परिवार की भलाई सुनिश्चित करें, जो तेज और सटीक तापमान रीडिंग के लिए डिज़ाइन किया गया है। चाहे आपको बुखार की जांच करनी हो या शरीर के तापमान में बदलाव को ट्रैक करना हो, यह आवश्यक उपकरण सेकंडों में सटीक परिणाम देता है। डिजिटल डिस्प्ले और मेमोरी रिकॉल के साथ, अपने स्वास्थ्य पर नज़र रखना पहले से कहीं अधिक सरल हो गया है।",
      covidtestkit: "कोविड टेस्ट किट: अपने और अपने आस-पास के लोगों की सुरक्षा सुनिश्चित करें हमारी विश्वसनीय कोविड टेस्ट किट के साथ, जो घर बैठे त्वरित और सटीक परिणाम देती है। आसान निर्देश और त्वरित परीक्षण क्षमताओं के साथ, आप कुछ ही मिनटों में वायरस की उपस्थिति का पता लगा सकते हैं, जिससे स्वास्थ्य और सुरक्षा के बारे में समय पर निर्णय लेना संभव हो जाता है। यह सार्वजनिक स्वास्थ्य और भलाई को प्राथमिकता देने वाले किसी भी व्यक्ति के लिए अनिवार्य है।",
      firstaidkit: "फर्स्ट एड किट: मामूली चोटों और आपात स्थितियों के लिए तैयार रहें हमारे व्यापक फर्स्ट एड किट के साथ। पट्टियों, एंटीसेप्टिक वाइप्स और अन्य आवश्यक चिकित्सा आपूर्ति से सुसज्जित, यह किट आपको ऑन-द-स्पॉट उपचार के लिए आवश्यक सब कुछ प्रदान करती है। कॉम्पैक्ट और पोर्टेबल, यह घर, यात्रा, या बाहरी गतिविधियों के लिए आदर्श है, यह सुनिश्चित करते हुए कि आप अप्रत्याशित स्थितियों से निपटने के लिए हमेशा तैयार हैं।",
      pulseoximeter: "पल्स ऑक्सीमीटर: अपने ऑक्सीजन स्तर और हृदय गति पर नज़र रखें हमारे कॉम्पैक्ट और उपयोग में आसान पल्स ऑक्सीमीटर के साथ। यह गैर-आक्रामक उपकरण केवल एक फिंगरप्लेसमेंट के साथ त्वरित और सटीक रीडिंग देता है, जिससे आप किसी भी समय अपने स्वास्थ्य की निगरानी कर सकते हैं। श्वसन स्थितियों और फिटनेस ट्रैकिंग के लिए आदर्श, यह आपके कल्याण को बनाए रखने के लिए एक महत्वपूर्ण उपकरण है।",
      pregnancytestkit: "गर्भावस्था परीक्षण किट: हमारे आसान-से-उपयोग वाले गर्भावस्था परीक्षण किट के साथ स्पष्ट और विश्वसनीय परिणाम प्राप्त करें, जो तेजी से और सटीक उत्तर प्रदान करने के लिए डिज़ाइन किया गया है। सरल निर्देशों और उच्च संवेदनशीलता के साथ, यह कुछ ही मिनटों में गर्भावस्था की पुष्टि कर देता है। महिलाओं के लिए यह विश्वसनीय साथी है जो सटीक प्रजनन स्वास्थ्य जानकारी प्राप्त करना चाहती हैं।",
      whoarewe: "हम कौन हैं",
      whoarewecontent1: "मेडिकोज़ एक व्यापक स्वास्थ्य प्लेटफ़ॉर्म प्रदान करता है जो मशीन लर्निंग का उपयोग करके व्यक्तिगत रोग की गंभीरता की भविष्यवाणी करता है, जिससे उपयोगकर्ताओं को मधुमेह, उच्च रक्तचाप, हृदय रोग आदि जैसी स्थितियों का प्रबंधन करने में मदद मिलती है।",
      whoarewecontent2: "यह प्लेटफ़ॉर्म उपयोगकर्ताओं को उनकी स्वास्थ्य आवश्यकताओं के आधार पर शीर्ष डॉक्टरों और क्लीनिकों से जोड़ता है और आवश्यक स्वास्थ्य निगरानी उपकरणों की सुविधाजनक खरीदारी विकल्प भी प्रदान करता है।",
      whoarewepoint1: "एआई इनसाइट्स के साथ व्यक्तिगत रोग भविष्यवाणियाँ।",
      whoarewepoint2: "उपयोगकर्ताओं के लिए सूचित स्वास्थ्य निर्णय लेना आसान बनाएं।",
      whoarewepoint3: "देश के शीर्ष डॉक्टरों और क्लीनिकों से जुड़ें।",
      whoarewepoint4: "स्वास्थ्य उपकरणों को आसानी से ऑनलाइन खरीदें।",
      whoarewepoint5: "बेहतर देखभाल के लिए व्यक्तिगत प्रदाता सिफारिशें।",
      whoarewepoint6: "प्रोएक्टिव स्वास्थ्य प्रबंधन के लिए सटीक इनसाइट्स।",
      weoffer: "हम आपकी सेहत सुधारने के लिए ",
      toimprove: "विभिन्न सेवाएँ प्रदान करते हैं।",
      keepup: "हमारी नवीनतम चिकित्सा खबरों से अपडेट रहें।",
      tagline: "आज का निदान, कल की सुरक्षा।",
      address: "456 लोटस स्ट्रीट, ब्लॉक C, सेक्टर 22, गुरुग्राम, हरियाणा, 122001, भारत",
      followus: "इंस्टाग्राम पर हमारा अनुसरण करें",
      trustus: "आपका विश्वसनीय स्वास्थ्य साथी, जो विशेषज्ञ देखभाल और व्यक्तिगत उपचार योजनाएँ प्रदान करता है। साथ मिलकर, हम आपके कल्याण को प्राथमिकता देते हैं, यह सुनिश्चित करते हैं कि आपका कल स्वस्थ और खुशहाल हो।",
      servicesContent: "मेडिकोज़ में, हम स्वास्थ्य परिणामों को सुधारने और पुरानी बीमारियों के प्रबंधन के लिए डिज़ाइन की गई सेवाओं की एक व्यापक श्रृंखला प्रदान करते हैं। हमारे विशेषज्ञ स्वास्थ्य सेवा पेशेवरों की टीम व्यक्तिगत देखभाल को नवीनतम चिकित्सा प्रौद्योगिकी के साथ मिलाकर निम्नलिखित सेवाएँ प्रदान करती है:",
      hypertensionService: "हम रक्तचाप प्रबंधन के लिए व्यक्तिगत निगरानी और उपचार योजनाएँ प्रदान करते हैं, जिसमें कार्डियोलॉजिस्ट और आहार विशेषज्ञों से नियमित परामर्श शामिल है। आप घरेलू ब्लड प्रेशर मॉनिटरिंग उपकरणों का उपयोग कर सकते हैं और जीवनशैली में बदलाव के कार्यक्रमों में भाग ले सकते हैं जो उच्च रक्तचाप को नियंत्रित करने में मदद करते हैं।",
      dementiaService: "डिमेंशिया देखभाल के लिए, हम बीमारी की प्रगति को धीमा करने के लिए संज्ञानात्मक पुनर्वास कार्यक्रम प्रदान करते हैं। हमारी विशेष स्मृति देखभाल सेवाएँ 24/7 समर्थन सुनिश्चित करती हैं, जबकि देखभाल करने वालों को रोगियों के लिए एक सुरक्षित और सहायक वातावरण बनाने के लिए मार्गदर्शन दिया जाता है।",
      aidsService: "हम एचआईवी/एड्स देखभाल की व्यापक सेवाएँ प्रदान करते हैं, जिसमें बीमारी को प्रभावी ढंग से प्रबंधित करने के लिए एंटीरेट्रोवायरल थेरेपी (ART) की पहुँच शामिल है। नियमित स्वास्थ्य परीक्षण प्रतिरक्षा प्रणाली की क्रियाशीलता और वायरल लोड की निगरानी करते हैं, और हमारी परामर्श सेवाएँ मानसिक स्वास्थ्य सहायता और जीवनशैली सलाह प्रदान करती हैं।",
      heartDiseaseService: "हम संपूर्ण हृदय स्वास्थ्य जांच प्रदान करते हैं, जिसमें कोलेस्ट्रॉल और तनाव परीक्षण शामिल हैं, साथ ही दवाओं से लेकर उन्नत प्रक्रियाओं जैसे एंजियोप्लास्टी तक उपचार भी शामिल हैं। हमारे कार्डियक पुनर्वास कार्यक्रम पुनर्प्राप्ति में मदद करते हैं और भविष्य की हृदय रोग की घटनाओं को रोकते हैं।",
      diabetesService: "हमारी मधुमेह प्रबंधन सेवाओं में उन्नत ग्लूकोज मीटर के साथ रक्त शर्करा की निगरानी शामिल है। हम व्यक्तिगत आहार योजनाएँ और व्यायाम योजनाएँ बनाते हैं और मधुमेह शिक्षा कार्यक्रम प्रदान करते हैं ताकि आप अपनी स्थिति को बेहतर ढंग से समझ सकें और उसका प्रबंधन कर सकें।"
    
    
  },

  spanish: {
    home: "Inicio",
    aboutus: "Sobre Nosotros",
    services: "Servicios",
    doctor: "Doctor",
    login: "Iniciar Sesión",
    connectwithus: "Conéctate con Nosotros",
    name: "Nombre",
    email: "Correo Electrónico",
    phonenumber: "Número de Teléfono",
    message: "Mensaje",
    submitnow: "Envíalo Ahora",
    conveyyour: "Comunica Tu",
    ideastous: "Ideas a Nosotros",
    getintouch: "PONTE EN CONTACTO",
    connecting: "Conectando",
    patients: "Pacientes",
    toqualitycare: "A la Atención de Calidad",
    submit: "Enviar",
    maincontainerslogan:
      "Tu socio de confianza en salud y bienestar, brindando atención experta y planes de tratamiento personalizados. Juntos, priorizamos tu bienestar, asegurando un mañana más saludable y feliz.",
    enquirynow: "Consulta Ahora",
    address: "456 Calle Lotus, Bloque C, Sector 22, Haryana",
    contactpageslogan:
      "Contáctanos para preguntas, asistencia técnica o oportunidades de colaboración a través de la información de contacto proporcionada.",
    profile: "Perfil",
    login: "Acceso",
    languages: "Idiomas",
      password: "Contraseña",
      forgotpassword: "Olvidé mi contraseña",
      resetpassword: "Restablecer contraseña",
      changepassword: "Cambiar contraseña",
      signUp: "Regístrate",
      remember: "Recuérdame",
      haveAccount: "¿Ya tienes una cuenta?",
      signIn: "Iniciar sesión",
      buyNow: "Compra ahora",
      shopping: "Compras",
      glucosemeter: "Glucómetro: Controla tu salud con nuestro avanzado glucómetro, diseñado para una monitorización rápida y precisa de los niveles de azúcar en la sangre. Ideal para el manejo de la diabetes, este dispositivo ofrece lecturas precisas con una simple punción en el dedo. Compacto y fácil de usar, es una herramienta esencial para rastrear tus niveles de glucosa con facilidad. Con características como pantalla digital, almacenamiento de memoria y conectividad con smartphones, gestionar tu azúcar en sangre es más fácil y conveniente que nunca.",
      bloodpressuremonitor: "Monitor de presión arterial: Controla la salud de tu corazón con nuestro confiable monitor de presión arterial. Este dispositivo fácil de usar ofrece resultados precisos y rápidos, permitiéndote monitorear la presión sistólica y diastólica, así como la frecuencia cardíaca desde la comodidad de tu hogar. Su pantalla digital y función de memoria facilitan el seguimiento de las tendencias a lo largo del tiempo, manteniéndote siempre informado y en control.",
      thermometer: "Termómetro: Asegura el bienestar de tu familia con nuestro termómetro fácil de usar, diseñado para lecturas de temperatura rápidas y precisas. Ya sea que necesites verificar fiebre o rastrear cambios en la temperatura corporal, este dispositivo esencial proporciona resultados precisos en segundos. Con pantalla digital y recuerdo de memoria, hacer un seguimiento de tu salud nunca ha sido tan sencillo.",
      covidtestkit: "Kit de prueba de COVID: Asegura tu seguridad y la de los que te rodean con nuestro confiable kit de prueba de COVID, que proporciona resultados rápidos y precisos en casa. Con instrucciones simples y capacidades de prueba rápida, puedes detectar la presencia del virus en minutos, permitiendo tomar decisiones informadas sobre salud y seguridad a tiempo. Es esencial para cualquier persona que priorice la salud pública y el bienestar.",
      firstaidkit: "Kit de primeros auxilios: Prepárate para lesiones menores y emergencias con nuestro completo kit de primeros auxilios. Equipado con vendajes, toallitas antisépticas y otros suministros médicos esenciales, este kit proporciona todo lo necesario para el tratamiento en el lugar. Compacto y portátil, es ideal para el hogar, viajes o actividades al aire libre, asegurando que siempre estés listo para enfrentar situaciones inesperadas.",
      pulseoximeter: "Oxímetro de pulso: Monitorea tus niveles de oxígeno y frecuencia cardíaca con nuestro oxímetro de pulso compacto y fácil de usar. Este dispositivo no invasivo proporciona lecturas rápidas y precisas con solo colocar un dedo, permitiéndote monitorear tu salud en cualquier momento. Ideal para condiciones respiratorias y seguimiento del estado físico, es una herramienta esencial para mantener tu bienestar.",
      pregnancytestkit: "Kit de prueba de embarazo: Obtén resultados claros y confiables con nuestro kit de prueba de embarazo fácil de usar, diseñado para proporcionar respuestas rápidas y precisas. Con instrucciones simples y alta sensibilidad, confirma el embarazo en minutos. Es el compañero confiable para mujeres que buscan obtener información precisa sobre salud reproductiva.",
      whoarewe: "¿Quiénes somos?",
      whoarewecontent1: "Medicoz ofrece una plataforma integral de salud que utiliza aprendizaje automático para predecir la gravedad de enfermedades individuales, ayudando a los usuarios a gestionar condiciones como diabetes, hipertensión y enfermedades cardíacas.",
      whoarewecontent2: "Esta plataforma conecta a los usuarios con los mejores doctores y clínicas según sus necesidades de salud y también ofrece opciones convenientes para la compra de equipos de monitoreo de salud.",
      whoarewepoint1: "Predicciones de enfermedades personalizadas con inteligencia artificial.",
      whoarewepoint2: "Facilita la toma de decisiones informadas sobre salud para los usuarios.",
      whoarewepoint3: "Conéctate con los mejores doctores y clínicas del país.",
      whoarewepoint4: "Compra equipos de salud en línea fácilmente.",
      whoarewepoint5: "Recomendaciones de proveedores personalizadas para una mejor atención.",
      whoarewepoint6: "Información precisa para una gestión proactiva de la salud.",
      weoffer: "Ofrecemos una variedad de",
      toimprove:"servicios para mejorar tu salud.",
      keepup: "Mantente actualizado con nuestras últimas noticias médicas.",
      tagline: "Diagnóstico de hoy, seguridad de mañana.",
      address: "456 Lotus Street, Bloque C, Sector 22, Gurugram, Haryana, 122001, India",
      followus: "Síguenos en Instagram",
      trustus: "Tu compañero de salud confiable, que ofrece atención experta y planes de tratamiento personalizados. Juntos, priorizamos tu bienestar, asegurando que tu mañana sea saludable y feliz.",
      servicesContent: "En Medicoz, ofrecemos una amplia gama de servicios diseñados para mejorar los resultados de salud y manejar enfermedades crónicas. Nuestro equipo de profesionales de salud combina cuidado personalizado con la última tecnología médica para ofrecer los siguientes servicios:",
      hypertensionService: "Ofrecemos monitoreo personalizado y planes de tratamiento para la gestión de la presión arterial, que incluyen consultas regulares con cardiólogos y nutricionistas. Puedes usar dispositivos de monitoreo de presión arterial en el hogar y participar en programas de cambio de estilo de vida que ayudan a controlar la hipertensión.",
      dementiaService: "Para el cuidado de la demencia, ofrecemos programas de rehabilitación cognitiva para ralentizar la progresión de la enfermedad. Nuestros servicios especializados de cuidado de la memoria aseguran apoyo las 24 horas del día, mientras guiamos a los cuidadores para crear un entorno seguro y de apoyo para los pacientes.",
      aidsService: "Brindamos servicios integrales para el cuidado del VIH/SIDA, que incluyen acceso a terapia antirretroviral (TAR) para manejar la enfermedad de manera efectiva. Los exámenes de salud regulares monitorean la funcionalidad del sistema inmunológico y la carga viral, y nuestros servicios de asesoramiento proporcionan apoyo en salud mental y consejos sobre estilo de vida.",
      heartDiseaseService: "Ofrecemos chequeos completos de salud cardíaca, que incluyen pruebas de colesterol y estrés, así como tratamientos que van desde medicamentos hasta procedimientos avanzados como la angioplastia. Nuestros programas de rehabilitación cardíaca ayudan en la recuperación y previenen futuros episodios de enfermedad cardíaca.",
      diabetesService: "Nuestros servicios de manejo de diabetes incluyen monitoreo de azúcar en sangre con glucómetros avanzados. Creamos planes de dieta y ejercicio personalizados y ofrecemos programas de educación sobre diabetes para ayudarte a comprender mejor y manejar tu condición."
    
  },

  urdu: {
    home: "گھر",
    aboutus: "ہمارے بارے میں",
    services: "خدمات",
    doctor: "ڈاکٹر",
    login: "لاگ ان",
    connectwithus: "ہم سے جڑیں",
    name: "نام",
    email: "ای میل",
    phonenumber: "فون نمبر",
    message: "پیغام",
    submitnow: "اب بھیجیں",
    conveyyour: "اپنا",
    ideastous: "خیالات ہمیں",
    getintouch: "رابطہ کریں",
    connecting: "منسلک ہو رہا ہے",
    patients: "مریض",
    toqualitycare: "معیاری دیکھ بھال کے لیے",
    submit: "جمع کریں",
    maincontainerslogan:
      "آپ کی صحت اور تندرستی میں قابل اعتماد ساتھی، ماہر دیکھ بھال اور ذاتی نوعیت کے علاج کے منصوبے فراہم کرنا۔ ہم مل کر آپ کی بھلائی کو ترجیح دیتے ہیں، ایک صحت مند اور خوشحال کل کو یقینی بناتے ہیں۔",
    enquirynow: "ابھی پوچھیں",
    address: "456 لوٹس اسٹریٹ، بلاک سی، سیکٹر 22، ہریانہ",
    contactpageslogan:
      "سوالات، تکنیکی مدد، یا تعاون کے مواقع کے لیے ہم سے رابطہ کریں فراہم کردہ رابطے کی معلومات کے ذریعے۔",
    profile: "پروفائل",
    login: "لاگ ان",
    languages: "زبانیں",
      password: "پاس ورڈ",
      forgotpassword: "پاس ورڈ بھول گئے",
      resetpassword: "پاس ورڈ دوبارہ سیٹ کریں",
      changepassword: "پاس ورڈ تبدیل کریں",
      signUp: "سائن اپ کریں",
      remember: "مجھے یاد رکھیں",
      haveAccount: "کیا آپ کے پاس پہلے سے اکاؤنٹ ہے؟",
      signIn: "سائن ان کریں",
      buyNow: "اب خریدیں",
      shopping: "خریداری",
      glucosemeter: "گلوکوز میٹر: اپنے صحت پر کنٹرول حاصل کریں ہمارے جدید گلوکوز میٹر کے ساتھ، جو خون کی شکر کی تیز اور درست نگرانی کے لئے ڈیزائن کیا گیا ہے۔ ذیابیطس کے انتظام کے لئے مثالی، یہ آلہ سادہ انگلی چُھپ سے درست پڑھن دیتا ہے۔ کمپیکٹ اور استعمال میں آسان، یہ ضروری آلہ آپ کو اپنے گلوکوز کی سطح کو آسانی سے ٹریک کرنے میں مدد دیتا ہے۔ ڈیجیٹل ڈسپلے، میموری اسٹوریج، اور اسمارٹ فون کنیکٹیوٹی جیسی خصوصیات کے ساتھ، آپ کے خون کی شکر کا انتظام پہلے سے کہیں زیادہ آسان اور آرام دہ ہو گیا ہے۔",
      bloodpressuremonitor: "بلڈ پریشر مانیٹر: اپنے دل کی صحت پر نظر رکھیں ہمارے قابل اعتماد بلڈ پریشر مانیٹر کے ساتھ۔ یہ صارف دوست آلہ درست اور تیز نتائج فراہم کرتا ہے، جس سے آپ گھر بیٹھے sistolic اور diastolic دباؤ کے ساتھ ساتھ دل کی دھڑکن کی نگرانی کر سکتے ہیں۔ اس کی ڈیجیٹل ڈسپلے اور میموری فنکشن وقت کے ساتھ رجحانات کی نگرانی کو آسان بناتا ہے، جس سے آپ ہمیشہ باخبر اور کنٹرول میں رہ سکتے ہیں۔",
      thermometer: "تھرمامیٹر: اپنے خاندان کی فلاح و بہبود کو یقینی بنائیں ہمارے استعمال میں آسان تھرمامیٹر کے ساتھ، جو تیز اور درست درجہ حرارت کی پڑھائی کے لئے ڈیزائن کیا گیا ہے۔ چاہے آپ کو بخار چیک کرنا ہو یا جسم کے درجہ حرارت میں تبدیلیوں کو ٹریک کرنا ہو، یہ ضروری آلہ سیکنڈوں میں درست نتائج دیتا ہے۔ ڈیجیٹل ڈسپلے اور میموری ریکال کے ساتھ، آپ کی صحت پر نظر رکھنا پہلے سے کہیں زیادہ آسان ہو گیا ہے۔",
      covidtestkit: "کووڈ ٹیسٹ کٹ: اپنے اور اپنے ارد گرد کے لوگوں کی حفاظت کو یقینی بنائیں ہمارے قابل اعتماد کووڈ ٹیسٹ کٹ کے ساتھ، جو گھر بیٹھے تیز اور درست نتائج فراہم کرتا ہے۔ آسان ہدایات اور فوری ٹیسٹنگ کی صلاحیتوں کے ساتھ، آپ چند منٹوں میں وائرس کی موجودگی کا پتہ لگا سکتے ہیں، جس سے صحت اور حفاظت کے بارے میں بروقت فیصلے کرنا ممکن ہوتا ہے۔ یہ عوامی صحت اور فلاح و بہبود کو ترجیح دینے والے کسی بھی شخص کے لئے لازمی ہے۔",
      firstaidkit: "فرسٹ ایڈ کٹ: معمولی چوٹوں اور ایمرجنسی حالات کے لئے تیار رہیں ہمارے جامع فرسٹ ایڈ کٹ کے ساتھ۔ پٹیوں، اینٹی سیپٹک وائپس اور دیگر ضروری طبی سامان سے لیس، یہ کٹ آپ کو موقع پر علاج کے لئے ضروری سب کچھ فراہم کرتی ہے۔ کمپیکٹ اور پورٹیبل، یہ گھر، سفر، یا بیرونی سرگرمیوں کے لئے مثالی ہے، اس بات کو یقینی بناتے ہوئے کہ آپ غیر متوقع حالات سے نمٹنے کے لئے ہمیشہ تیار ہیں۔",
      pulseoximeter: "پلس آکسی میٹر: اپنے آکسیجن کی سطح اور دل کی دھڑکن پر نظر رکھیں ہمارے کمپیکٹ اور استعمال میں آسان پلس آکسی میٹر کے ساتھ۔ یہ غیر مداخلت کرنے والا آلہ صرف ایک انگلی کی جگہ کے ساتھ تیز اور درست پڑھائیاں دیتا ہے، جس سے آپ کسی بھی وقت اپنی صحت کی نگرانی کر سکتے ہیں۔ سانس کی حالتوں اور فٹنس ٹریکنگ کے لئے مثالی، یہ آپ کی فلاح و بہبود کو برقرار رکھنے کے لئے ایک اہم آلہ ہے۔",
      pregnancytestkit: "حمل کی ٹیسٹ کٹ: ہمارے استعمال میں آسان حمل کی ٹیسٹ کٹ کے ساتھ واضح اور قابل اعتماد نتائج حاصل کریں، جو تیز اور درست جوابات فراہم کرنے کے لئے ڈیزائن کی گئی ہے۔ سادہ ہدایات اور اعلی حساسیت کے ساتھ، یہ چند منٹوں میں حمل کی تصدیق کر دیتی ہے۔ خواتین کے لئے یہ قابل اعتماد ساتھی ہے جو درست تولیدی صحت کی معلومات حاصل کرنا چاہتی ہیں۔",
      whoarewe: "ہم کون ہیں",
      whoarewecontent1: "میڈیکوز ایک جامع صحت پلیٹ فارم فراہم کرتا ہے جو مشین لرننگ کا استعمال کرکے ذاتی بیماری کی شدت کی پیش گوئی کرتا ہے، جس سے صارفین کو ذیابیطس، ہائی بلڈ پریشر، دل کی بیماری وغیرہ جیسے حالات کا انتظام کرنے میں مدد ملتی ہے۔",
      whoarewecontent2: "یہ پلیٹ فارم صارفین کو ان کی صحت کی ضروریات کی بنیاد پر سرکردہ ڈاکٹروں اور کلینکس سے جوڑتا ہے اور ضروری صحت کی نگرانی کے آلات کی سہولت کے ساتھ خریداری کے اختیارات بھی فراہم کرتا ہے۔",
      whoarewepoint1: "AI بصیرت کے ساتھ ذاتی بیماری کی پیش گوئیاں۔",
      whoarewepoint2: "صارفین کے لئے معلوماتی صحت کے فیصلے کرنا آسان بنائیں۔",
      whoarewepoint3: "ملک کے سرکردہ ڈاکٹروں اور کلینکس سے جڑیں۔",
      whoarewepoint4: "صحت کے آلات کو آن لائن آسانی سے خریدیں۔",
      whoarewepoint5: "بہتر دیکھ بھال کے لئے ذاتی فراہم کنندہ کی سفارشات۔",
      whoarewepoint6: "پرو ایکٹو صحت ک انتظام کے لئے درست بصیرت۔",
      weoffer: "ہم آپ کی صحت کو بہتر بنانے کے لئ",
      toimprove:"مختلف خدمات فراہم کرتے ہیں۔",
      keepup: "ہماری تازہ ترین طبی خبروں سے اپ ڈیٹ رہیں۔",
      tagline: "آج کی تشخیص، کل کی حفاظت۔",
      address: "456 لوٹس اسٹریٹ، بلاک C، سیکٹر 22، گروگرام، ہریانہ، 122001، بھارت",
      followus: "انسٹاگرام پر ہمیں فالو کریں",
      trustus: "آپ کا قابل اعتماد صحت کا ساتھی، جو ماہر دیکھ بھال اور ذاتی علاج کے منصوبے فراہم کرتا ہے۔ مل کر، ہم آپ کی فلاح و بہبود کو ترجیح دیتے ہیں، اس بات کو یقینی بناتے ہیں کہ آپ کا کل صحت مند اور خوشحال ہو۔",
      servicesContent: "میڈیکوز میں، ہم صحت کے نتائج کو بہتر بنانے اور دائمی بیماریوں کا انتظام کرنے کے لئے ڈیزائن کی گئی خدمات کی ایک جامع رینج فراہم کرتے ہیں۔ ہمارے ماہر صحت کے پیشہ ور افراد کی ٹیم ذاتی دیکھ بھال کو جدید طبی ٹیکنالوجی کے ساتھ ملا کر مندرجہ ذیل خدمات فراہم کرتی ہے:",
      hypertensionService: "ہم بلڈ پریشر کے انتظام کے لئے ذاتی نگرانی اور علاج کے منصوبے فراہم کرتے ہیں، جس میں کارڈیولوجسٹ اور غذائی ماہرین سے باقاعدہ مشاورت شامل ہے۔ آپ گھر میں بلڈ پریشر مانیٹرنگ کے آلات استعمال کر سکتے ہیں اور طرز زندگی میں تبدیلی کے پروگراموں میں حصہ لے سکتے ہیں جو ہائی بلڈ پریشر کو کنٹرول کرنے میں مدد دیتے ہیں۔",
      dementiaService: "دمینشیا کی دیکھ بھال کے لئے، ہم بیماری کی ترقی کو سست کرنے کے لئے علمی بحالی کے پروگرام فراہم کرتے ہیں۔ ہماری خصوصی یادداشت کی دیکھ بھال کی خدمات 24/7 مدد کی ضمانت دیتی ہیں، جبکہ نگہداشت کرنے والوں کو مریضوں کے لئے محفوظ اور معاون ماحول بنانے کے لئے رہنمائی کی جاتی ہے۔",
      aidsService: "ہم ایچ آئی وی/ایڈز کی دیکھ بھال کی جامع خدمات فراہم کرتے ہیں، جس میں بیماری کو مؤثر طریقے سے منظم کرنے کے لئے اینٹی ریٹرو وائرل تھراپی (ART) تک رسائی شامل ہے۔ باقاعدہ صحت کے ٹیسٹ مدافعتی نظام کی فعالیت اور وائرس کا بوجھ مانیٹر کرتے ہیں، اور ہماری مشاورت کی خدمات ذہنی صحت کی مدد اور طرز زندگی کی مشاورت فراہم کرتی ہیں۔",
      heartDiseaseService: "ہم مکمل دل کی صحت کی جانچ فراہم کرتے ہیں، جس میں کولیسٹرول اور تناؤ کی جانچ شامل ہے، ساتھ ہی ادویات سے لے کر جدید طریقہ کار جیسے اینجیوپلاسٹی تک علاج بھی شامل ہے۔ ہمارے کارڈیک بحالی کے پروگرام بحالی میں مدد دیتے ہیں اور دل کی بیماری کی آئندہ کی حالتوں کو روکنے میں مدد کرتے ہیں۔",
      diabetesService: "ہماری ذیابیطس کے انتظام کی خدمات میں جدید گلوکوز میٹر کے ساتھ خون کی شوگر کی نگرانی شامل ہے۔ ہم ذاتی غذا کے منصوبے اور ورزش کے منصوبے تیار کرتے ہیں اور ذیابیطس کی تعلیم کے پروگرام فراہم کرتے ہیں تاکہ آپ اپنی حالت کو بہتر طریقے سے سمجھ سکیں اور اس کا انتظام کر سکیں۔"
  },

  french: {
    home: "Accueil",
    aboutus: "À Propos de Nous",
    services: "Services",
    doctor: "Docteur",
    login: "Connexion",
    connectwithus: "Connectez-vous avec Nous",
    name: "Nom",
    email: "Email",
    phonenumber: "Numéro de Téléphone",
    message: "Message",
    submitnow: "Soumettre Maintenant",
    conveyyour: "Exprimez Votre",
    ideastous: "Idées à Nous",
    getintouch: "CONTACTEZ-NOUS",
    connecting: "connecter les",
    patients: "Patients",
    toqualitycare: "à des soins de qualité",
    submit: "Soumettre",
    maincontainerslogan:
      "Votre partenaire de confiance en santé et bien-être, offrant des soins experts et des plans de traitement personnalisés. Ensemble, nous priorisons votre bien-être, en veillant à un avenir plus sain et plus heureux.",
    enquirynow: "Demandez Maintenant",
    address: "456 Rue Lotus, Bloc C, Secteur 22, Haryana",
    contactpageslogan:
      "Contactez-nous pour des questions, une assistance technique ou des opportunités de collaboration via les coordonnées fournies.",
    profile: "Profil",
    login: "Connexion",
    languages: "Langages",
      password: "Mot de passe",
      forgotpassword: "Mot de passe oublié",
      resetpassword: "Réinitialiser le mot de passe",
      changepassword: "Changer le mot de passe",
      signUp: "S'inscrire",
      remember: "Se souvenir de moi",
      haveAccount: "Vous avez déjà un compte",
      signIn: "Se connecter",
      buyNow: "Achetez maintenant",
      shopping: "Shopping",
      glucosemeter: "Glucomètre : Gardez le contrôle de votre santé avec notre glucomètre avancé, conçu pour une surveillance rapide et précise de la glycémie. Idéal pour la gestion du diabète, cet appareil fournit des lectures précises à partir d'une simple piqûre au doigt. Compact et facile à utiliser, cet outil essentiel vous aide à suivre facilement votre taux de glucose. Avec des fonctionnalités telles qu'un affichage numérique, un stockage de mémoire et une connectivité avec les smartphones, la gestion de votre glycémie est devenue plus facile et plus pratique que jamais.",
      bloodpressuremonitor: "Moniteur de pression artérielle : Surveillez la santé de votre cœur avec notre moniteur de pression artérielle fiable. Cet appareil convivial fournit des résultats précis et rapides, vous permettant de surveiller la pression systolique et diastolique ainsi que la fréquence cardiaque depuis chez vous. Son affichage numérique et sa fonction de mémoire facilitent le suivi des tendances au fil du temps, vous permettant de rester informé et en contrôle.",
      thermometer: "Thermomètre : Assurez le bien-être de votre famille avec notre thermomètre facile à utiliser, conçu pour des mesures de température rapides et précises. Que vous ayez besoin de vérifier une fièvre ou de suivre les variations de température corporelle, cet outil essentiel fournit des résultats précis en quelques secondes. Avec un affichage numérique et une fonction de rappel de mémoire, suivre votre santé est devenu plus simple que jamais.",
      covidtestkit: "Kit de test COVID : Assurez la sécurité de vous-même et de vos proches avec notre kit de test COVID fiable, qui fournit des résultats rapides et précis à domicile. Avec des instructions faciles et des capacités de test rapides, vous pouvez détecter la présence du virus en quelques minutes, permettant des décisions opportunes sur la santé et la sécurité. C'est essentiel pour toute personne qui privilégie la santé publique et le bien-être.",
      firstaidkit: "Trousse de premiers secours : Soyez prêt pour les blessures mineures et les urgences avec notre trousse de premiers secours complète. Équipée de bandages, de lingettes antiseptiques et d'autres fournitures médicales essentielles, cette trousse vous fournit tout ce dont vous avez besoin pour des soins immédiats. Compacte et portable, elle est idéale pour la maison, les voyages ou les activités en plein air, garantissant que vous êtes toujours prêt à faire face à des situations imprévues.",
      pulseoximeter: "Oxymètre de pouls : Surveillez votre taux d'oxygène et votre fréquence cardiaque avec notre oxymètre de pouls compact et facile à utiliser. Cet appareil non invasif fournit des lectures rapides et précises avec un simple placement du doigt, vous permettant de surveiller votre santé à tout moment. Idéal pour les conditions respiratoires et le suivi de la forme physique, c'est un outil essentiel pour maintenir votre bien-être.",
      pregnancytestkit: "Kit de test de grossesse : Obtenez des résultats clairs et fiables avec notre kit de test de grossesse facile à utiliser, conçu pour fournir des réponses rapides et précises. Avec des instructions simples et une grande sensibilité, il confirme la grossesse en quelques minutes. C'est un compagnon fiable pour les femmes qui souhaitent obtenir des informations précises sur leur santé reproductive.",
      whoarewe: "Qui sommes-nous",
      whoarewecontent1: "Medicoz fournit une plateforme de santé complète qui utilise l'apprentissage automatique pour prédire la gravité des maladies personnelles, aidant les utilisateurs à gérer des conditions telles que le diabète, l'hypertension, les maladies cardiaques, etc.",
      whoarewecontent2: "Cette plateforme connecte les utilisateurs avec les meilleurs médecins et cliniques en fonction de leurs besoins de santé et offre également des options d'achat pratiques pour les équipements de surveillance de la santé nécessaires.",
      whoarewepoint1: "Prévisions de maladies personnalisées avec des informations basées sur l'IA.",
      whoarewepoint2: "Faciliter la prise de décisions en matière de santé éclairées pour les utilisateurs.",
      whoarewepoint3: "Connectez-vous avec les meilleurs médecins et cliniques du pays.",
      whoarewepoint4: "Achetez facilement des équipements de santé en ligne.",
      whoarewepoint5: "Recommandations personnalisées des prestataires pour de meilleurs soins.",
      whoarewepoint6: "Informations précises pour une gestion proactive de la santé.",
      weoffer: "Nous proposons divers services", 
      toimprove:"pour améliorer votre santé.",
      keepup: "Restez à jour avec nos dernières nouvelles médicales.",
      tagline: "Diagnostic d'aujourd'hui, sécurité de demain.",
      address: "456 Lotus Street, Block C, Sector 22, Gurgaon, Haryana, 122001, Inde",
      followus: "Suivez-nous sur Instagram",
      trustus: "Votre partenaire de santé de confiance, offrant des soins experts et des plans de traitement personnalisés. Ensemble, nous mettons votre bien-être en priorité, en veillant à ce que votre demain soit sain et heureux.",
      servicesContent: "Chez Medicoz, nous proposons une gamme complète de services conçus pour améliorer les résultats de santé et gérer les maladies chroniques. Notre équipe de professionnels de la santé experts fournit des soins personnalisés en combinant les dernières technologies médicales avec les services suivants :",
      hypertensionService: "Nous fournissons des plans de surveillance et de traitement personnalisés pour la gestion de l'hypertension, y compris des consultations régulières avec des cardiologues et des diététiciens. Vous pouvez utiliser des dispositifs de surveillance de la pression artérielle à domicile et participer à des programmes de changement de mode de vie qui aident à contrôler l'hypertension.",
      dementiaService: "Pour les soins de démence, nous proposons des programmes de réhabilitation cognitive pour ralentir la progression de la maladie. Nos services de soins de mémoire spécialisés assurent un soutien 24/7, tout en guidant les soignants pour créer un environnement sûr et soutenant pour les patients.",
      aidsService: "Nous fournissons des services complets de soins du VIH/SIDA, y compris l'accès à une thérapie antirétrovirale (ART) pour gérer efficacement la maladie. Les examens de santé réguliers surveillent la fonctionnalité du système immunitaire et la charge virale, et nos services de conseil offrent un soutien en santé mentale et des conseils sur le mode de vie.",
      heartDiseaseService: "Nous proposons des examens complets de la santé cardiaque, y compris des tests de cholestérol et de stress, ainsi que des traitements allant des médicaments aux procédures avancées telles que l'angioplastie. Nos programmes de réhabilitation cardiaque aident à la récupération et à la prévention des futurs épisodes de maladie cardiaque.",
      diabetesService: "Nos services de gestion du diabète incluent la surveillance de la glycémie avec des glucomètres avancés. Nous élaborons des plans alimentaires personnalisés et des programmes d'exercice, et offrons des programmes d'éducation sur le diabète pour vous aider à mieux comprendre et gérer votre état."
  },
};


export default lang;
