const lang = {
  en: {
    home: "Home",
    aboutus: "About Us",
    services: "Services",
    doctor: "Doctor",
    login: "Login",
    connectwithus: "Connect with Us",
    name: "Name",
    email: "Email",
    phonenumber: "Phone Number",
    message: "Message",
    submitnow: "Submit Now",
    conveyyour: "Convey Your",
    ideastous: "Ideas To Us",
    getintouch: "GET IN TOUCH",
    connecting: "Connecting",
    patients: "Patients",
    toqualitycare: "To Quality Care",
    submit: "Submit",
    maincontainerslogan:
      "Your trusted partner in health and wellness, providing expert care and personalized treatment plans. Together, we prioritize your well-being, ensuring a healthier, happier tomorrow.",
    enquirynow: "Enquiry Now",
    address: "456 Lotus Street, Block C, Sector 22, Haryana",
    contactpageslogan:
      "Contact us for questions, technical assistance, or collaboration opportunities via the contact information provided.",
    profile: "Profile",
    login: "Login",
    languages: "Languages",
  },

  हिन्दी: {
    home: "होम",
    aboutus: "हमारे बारे में",
    services: "सेवाएं",
    doctor: "चिकित्सक",
    login: "लॉग इन",
    connectwithus: "हमारे साथ जुड़ें",
    name: "नाम",
    email: "ईमेल",
    phonenumber: "फ़ोन नंबर",
    message: "संदेश",
    submitnow: "जमा करें",
    conveyyour: "अपने विचार",
    ideastous: "हमें बताएं",
    getintouch: "संपर्क में रहे",
    submit: "जमा करें",
    connecting: "मरीजों को",
    patients: "गुणवत्तापूर्ण ",
    toqualitycare: "देखभाल से जोड़ना",
    maincontainerslogan:
      "स्वास्थ्य और कल्याण में आपका विश्वसनीय भागीदार, विशेषज्ञ देखभाल और वैयक्तिकृत उपचार योजनाएँ प्रदान करता है। साथ मिलकर, हम एक स्वस्थ, खुशहाल कल सुनिश्चित करते हुए आपकी भलाई को प्राथमिकता देते हैं।",
    enquirynow: "अभी पूछताछ करें",
    address: "456 लोटस स्ट्रीट, ब्लॉक सी, सेक्टर 22, हरयाणा",
    contactpageslogan:
      "प्रश्नों, तकनीकी सहायता, या सहयोग के अवसरों के लिए प्रदान की गई संपर्क जानकारी के माध्यम से हमसे संपर्क करें।",
    profile: "प्रोफ़ाइल",
    login: "लॉगिन",
    languages: "भाषा",
  },

  spanish: {
    home: "Inicio",
    aboutus: "Sobre Nosotros",
    services: "Servicios",
    doctor: "Doctor",
    login: "Iniciar Sesión",
    connectwithus: "Conéctate con Nosotros",
    name: "Nombre",
    email: "Correo Electrónico",
    phonenumber: "Número de Teléfono",
    message: "Mensaje",
    submitnow: "Envíalo Ahora",
    conveyyour: "Comunica Tu",
    ideastous: "Ideas a Nosotros",
    getintouch: "PONTE EN CONTACTO",
    connecting: "Conectando",
    patients: "Pacientes",
    toqualitycare: "A la Atención de Calidad",
    submit: "Enviar",
    maincontainerslogan:
      "Tu socio de confianza en salud y bienestar, brindando atención experta y planes de tratamiento personalizados. Juntos, priorizamos tu bienestar, asegurando un mañana más saludable y feliz.",
    enquirynow: "Consulta Ahora",
    address: "456 Calle Lotus, Bloque C, Sector 22, Haryana",
    contactpageslogan:
      "Contáctanos para preguntas, asistencia técnica o oportunidades de colaboración a través de la información de contacto proporcionada.",
    profile: "Perfil",
    login: "Acceso",
    languages: "Idiomas",
  },

  urdu: {
    home: "گھر",
    aboutus: "ہمارے بارے میں",
    services: "خدمات",
    doctor: "ڈاکٹر",
    login: "لاگ ان",
    connectwithus: "ہم سے جڑیں",
    name: "نام",
    email: "ای میل",
    phonenumber: "فون نمبر",
    message: "پیغام",
    submitnow: "اب بھیجیں",
    conveyyour: "اپنا",
    ideastous: "خیالات ہمیں",
    getintouch: "رابطہ کریں",
    connecting: "منسلک ہو رہا ہے",
    patients: "مریض",
    toqualitycare: "معیاری دیکھ بھال کے لیے",
    submit: "جمع کریں",
    maincontainerslogan:
      "آپ کی صحت اور تندرستی میں قابل اعتماد ساتھی، ماہر دیکھ بھال اور ذاتی نوعیت کے علاج کے منصوبے فراہم کرنا۔ ہم مل کر آپ کی بھلائی کو ترجیح دیتے ہیں، ایک صحت مند اور خوشحال کل کو یقینی بناتے ہیں۔",
    enquirynow: "ابھی پوچھیں",
    address: "456 لوٹس اسٹریٹ، بلاک سی، سیکٹر 22، ہریانہ",
    contactpageslogan:
      "سوالات، تکنیکی مدد، یا تعاون کے مواقع کے لیے ہم سے رابطہ کریں فراہم کردہ رابطے کی معلومات کے ذریعے۔",
    profile: "پروفائل",
    login: "لاگ ان",
    languages: "زبانیں",
  },

  french: {
    home: "Accueil",
    aboutus: "À Propos de Nous",
    services: "Services",
    doctor: "Docteur",
    login: "Connexion",
    connectwithus: "Connectez-vous avec Nous",
    name: "Nom",
    email: "Email",
    phonenumber: "Numéro de Téléphone",
    message: "Message",
    submitnow: "Soumettre Maintenant",
    conveyyour: "Exprimez Votre",
    ideastous: "Idées à Nous",
    getintouch: "CONTACTEZ-NOUS",
    connecting: "connecter les",
    patients: "Patients",
    toqualitycare: "à des soins de qualité",
    submit: "Soumettre",
    maincontainerslogan:
      "Votre partenaire de confiance en santé et bien-être, offrant des soins experts et des plans de traitement personnalisés. Ensemble, nous priorisons votre bien-être, en veillant à un avenir plus sain et plus heureux.",
    enquirynow: "Demandez Maintenant",
    address: "456 Rue Lotus, Bloc C, Secteur 22, Haryana",
    contactpageslogan:
      "Contactez-nous pour des questions, une assistance technique ou des opportunités de collaboration via les coordonnées fournies.",
    profile: "Profil",
    login: "Connexion",
    languages: "Langages",
  },
};

export default lang;
